### ISSUE TITLE
Connectivity between FVP and VMs in cca emulator

### ISSUE THREAD

**Issue by andreademurtas** [ArmDeveloperEcosystem/arm-learning-paths#814]
Hi, I'm using the armswdev/aemfvp-cca-image docker image following https://learn.arm.com/learning-paths/servers-and-cloud-computing/cca-container/cca-container/  for performing tests on ARM CCA, but I need to have connetivity between the FVP and the various vm realms. Is there any way of achieving this? Thanks.

**Comment by pareenaverma** [comment]
Hi @andreademurtas, thank you for opening this query.  Can you elaborate a little more on the use case? When you say connectivity from the FVP, do you mean connectivity from the application running in a confidential realm on the FVP? Where are the various vm realms running? Thanks

**Comment by andreademurtas** [comment]
Hello @pareenaverma, thank you for taking the time to respond. I will try to explain what my ideal setting is: I'd like to be able to
- Connect from the container to the FVP and viceversa
- Connect from the FVP to the realms and viceversa
- Connect from the container to the realms and viceversa
- (optional) Connect from a realm to another realm
I need to have this because I'm experimenting with a distributed setting where the container is acting as an external host, connecting to the FVP from the internet, and the services exposed by the FVP live in both normal world and realms. These services could be something like an HTTP server or specific runtime environments. I have tried using tap devices, but for now I managed to only be able to connect from a realm to the FVP and viceversa.

**Comment by paulhowardarm** [comment]
Hi @andreademurtas - I am part of the Arm team working on the software stack. I'd like to make sure that I understand your end-to-end requirements here in terms of networking communication, because there are a lot of layers. It will probably help if we can factor out the steps where you just need simple pass-through behaviour, and think purely in terms of which components of the system need to communicate with each other semantically.

Let's assume that there are two application workloads in your architecture: Server Workload and Client Workload. Let's further assume that the ultimate requirement is for those two pieces to be able to communicate over a regular protocol like HTTP.

One of the workloads will be running in a realm. Is that the Client or the Server? And where is the other workload running?

If you are willing to attach a blocks/arrows sketch of your intended environment, that would be useful to us in visualising.

**Comment by paulhowardarm** [comment]
Thank you @andreademurtas - this helps me to understand. I will do some investigation and get back to you.
