### ISSUE TITLE
Migrating C/C++ applications

### ISSUE THREAD

**Issue by daniel-thompson** [ArmDeveloperEcosystem/arm-learning-paths#876]
In the [Migrating applications to Arm servers](https://learn.arm.com/learning-paths/servers-and-cloud-computing/migration/c-c++/) pathway I was a little surprised to see Ubuntu 22.04 in the section on available compiler versions but not contemporary competitors like [Debian 12](https://aws.amazon.com/marketplace/pp/prodview-63gms6fbfaota?sr=0-1&ref_=beagle&applicationId=AWSMPContessa) and [RHEL 9](https://aws.amazon.com/marketplace/pp/prodview-jugq2ewzbalue?sr=0-37&ref_=beagle&applicationId=AWSMPContessa).

**Comment by B-Rich** [comment]
This is because Ubuntu has a larger user base and their toolchain has been being used by Genode. Its a pretty amazing Virtual Machine OS or project. Its been being developed at a University in Germany for the last 20 plus years I believe. Its know as L3 and L4 Family of microkernel VMs. And its open source too. Karlsruhe Institute of Technology https://en.wikipedia.org/wiki/Karlsruhe_Institute_of_Technology. Beautiful code too. They have everything in software that you can read and use. They used virtualbox for a long time. Then they finally tested it on hardware. The pandaboard and then the spartan 7 I think. Which was when they started using the Ubuntu Toolchain ti port and bootstrap it. They also use Fuse as well. And that was as few years ago. So I bet they have made even more progress and amazing discoveries since then. Its been the work of many Students and Professors over the last 25 years. And their goal was to create secure multi user gateway the public to use for  banking and such.

**Comment by jasonrandrews** [comment]
Hi @daniel-thompson,
We are happy to add addition distribution information. 
Would you be able to look up the default compiler versions for the distros you are interested in? 
Thanks,
Jason

**Comment by daniel-thompson** [comment]
Debian 12 "bookworm" offers gcc-11 and gcc-12 (with 12 being default) and clang-13, -14, -15 and -16 (with -14 being default)
RHEL9 offers gcc-11 and clang-13

**Comment by jasonrandrews** [comment]
Please confirm the PR at https://github.com/ArmDeveloperEcosystem/arm-learning-paths/pull/895 is correct.
